#cloud-config
# OCI Instance 自動設定腳本

package_update: true
package_upgrade: true

packages:
  - python3
  - python3-pip
  - git
  - cronie

write_files:
  - path: /home/opc/setup_crawler.sh
    permissions: '0755'
    owner: opc:opc
    content: |
      #!/bin/bash
      
      # 設定爬蟲環境
      cd /home/opc
      
      # 建立工作目錄
      mkdir -p taichung-building-crawler
      cd taichung-building-crawler
      
      # 從 Object Storage 下載爬蟲檔案
      export OCI_CLI_AUTH=instance_principal
      
      # 下載所有必要檔案
      oci os object get -bn taichung-building-permits -ns nrsdi1rz5vl8 --name scripts/optimized-crawler-stable.py --file optimized-crawler-stable.py --auth instance_principal
      oci os object get -bn taichung-building-permits -ns nrsdi1rz5vl8 --name scripts/cron_daily_crawler_v3.py --file cron_daily_crawler_v3.py --auth instance_principal
      oci os object get -bn taichung-building-permits -ns nrsdi1rz5vl8 --name scripts/backup_current_data.py --file backup_current_data.py --auth instance_principal
      oci os object get -bn taichung-building-permits -ns nrsdi1rz5vl8 --name scripts/baojia_companies.json --file baojia_companies.json --auth instance_principal
      
      # 建立每日執行腳本
      cat > daily_crawler_730am.sh << 'EOF'
      #!/bin/bash
      export OCI_CLI_AUTH=instance_principal
      export PATH="/home/opc/bin:$PATH"
      cd /home/opc/taichung-building-crawler
      
      echo "=========================================="
      echo "🕐 每日爬蟲開始: $(date '+%Y-%m-%d %H:%M:%S')"
      echo "=========================================="
      
      python3 cron_daily_crawler_v3.py >> cron_daily_7am.log 2>&1
      
      if [ $? -eq 0 ]; then
          echo "✅ 爬蟲執行成功"
          python3 backup_current_data.py >> cron_daily_7am.log 2>&1
      else
          echo "❌ 爬蟲執行失敗"
      fi
      
      echo "🕐 每日爬蟲結束: $(date '+%Y-%m-%d %H:%M:%S')"
      echo ""
      EOF
      
      chmod +x daily_crawler_730am.sh
      
      # 修改檔案中的路徑
      sed -i 's|/home/laija/bin/oci|oci|g' *.py
      sed -i 's|/mnt/c/claude code/建照爬蟲/oci|/home/opc/taichung-building-crawler|g' *.py
      
      # 安裝 Python 套件
      pip3 install --user requests beautifulsoup4
      
      # 設定 cron
      (crontab -l 2>/dev/null; echo "30 7 * * * /home/opc/taichung-building-crawler/daily_crawler_730am.sh") | crontab -
      
      echo "✅ 爬蟲環境設定完成！"

runcmd:
  - systemctl enable crond
  - systemctl start crond
  - su - opc -c '/home/opc/setup_crawler.sh'
  - echo "✅ Cloud-init 設定完成" > /home/opc/setup_complete.txt