#!/bin/bash

# Google Cloud 爬蟲設定腳本
echo "=== Google Cloud 爬蟲設定 ==="
echo ""
echo "請執行以下步驟："
echo ""
echo "1. 首先登入 Google Cloud："
echo "   gcloud auth login"
echo ""
echo "2. 設定專案："
echo "   gcloud config set project taichung-crawler"
echo ""
echo "3. 建立 Storage Bucket："
echo "   gsutil mb -l asia-east1 gs://taichung-crawler-permits"
echo ""
echo "4. 建立爬蟲實例："
echo "   gcloud compute instances create taichung-crawler \\"
echo "     --zone=asia-east1-b \\"
echo "     --machine-type=e2-micro \\"
echo "     --image-family=ubuntu-2204-lts \\"
echo "     --image-project=ubuntu-os-cloud \\"
echo "     --boot-disk-size=20GB \\"
echo "     --metadata-from-file=startup-script=/tmp/gcp_crawler_startup.sh \\"
echo "     --tags=http-server"
echo ""
echo "5. 等待實例建立完成後，SSH 連線："
echo "   gcloud compute ssh taichung-crawler --zone=asia-east1-b"
echo ""
echo "6. 檢查爬蟲執行狀態："
echo "   tail -f /home/crawler/crawler.log"
echo ""
echo "啟動腳本已儲存在: /tmp/gcp_crawler_startup.sh"